[build]
    command = "npm run build"
    functions = "functions"
    publish = "dist"

[dev]
    framework = "#custom"
    command = "npm run dev:webpack"
    targetPort = 5000
    port = 8000
    publish = "dist"
    autoLaunch = false
