[build]
    command = "npm run build"
    functions = "functions"
    publish = "dist"

[dev]
    framework = "#custom"
    command = "npm run dev:webpack"
    targetPort = 3000
    port = 5000
    publish = "dist"
    autoLaunch = false